name: Disassemble
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  disassemble:
    runs-on: ubuntu-latest
    environment: dev
    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH key
        run: |
          mkdir ~/.ssh
          chmod 700 ~/.ssh

          echo "${{ secrets.SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa.pub

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZ_CLIENT_ID }}
          tenant-id: ${{ secrets.AZ_TENANT_ID }}
          subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}

      - name: Init
        run: terraform init

      - name: Destroy
        run: terraform destroy -auto-approve
